version: '3.8'

services:
  finaltestauso123:
    image: finalimage:latest
    build: .
    container_name: finalautotest123
    ports:
      - "8030:3000"
    environment:
      - PORT=3000
    volumes:
    - ./:/app
    command: ["node", "index.js"]
